### ISSUE TITLE
fetchParity(): checksum mismatch

### ISSUE THREAD

**Issue by Kalibar** [paritytech/js-libs#211]
using parity electron:
`fetchParity(mainWindow, {
			onProgress: (prog) => {
				console.log(prog)
			},
			parityChannel: 'beta'
		})`

progressing to 1 on every retry, then:

`Error: Checksum mismatch, expecting 3896baa8939b8781fbfc437828b1242f8c87492e3699f1404435ab36fa441cbf, got 8285afbb5b72241ffe3c0d784ef4500e957caab8ccb5ce639fc48319dbc4900b`

**Comment by axelchalon** [comment]
hmm, cannot reproduce :/

the checksum you got `8285afbb5b72241ffe3c0d784ef4500e957caab8ccb5ce639fc48319dbc4900b` is the correct checksum for the latest linux beta. I don't know where the expected `3896baa8939b8781fbfc437828b1242f8c87492e3699f1404435ab36fa441cbf` is coming from.. we've had some checksum issues because of caching on the server side, but if you can reproduce this each time then it's not probably not it.. cc @amaurymartiny any idea?

**Comment by amaurymartiny** [comment]
I suspect it's a caching issue too.

@Kalibar Can you go to https://vanity-service.parity.io/parity-binaries?version=beta with your browser, and CTRL+F for both hashes, to see which hash it currently gives you?

**Comment by Kalibar** [comment]
Thanks for reply.
CTRL+F giving `8285afbb5b72241ffe3c0d784ef4500e957caab8ccb5ce639fc48319dbc4900b`
today when retrying, parity is loading fine. no error
does this happen often? if so, it would make sense to have parity already shipped with production app?

**Comment by amaurymartiny** [comment]
> does this happen often?

It happens unfortunately for a short period of time after each parity-ethereum release (so every ~6 weeks). From what we've seen it's a CDN caching issue, so we'll just need to make sure to clear the cache every time.

> it would make sense to have parity already shipped with production app

The function `fetchParity` does what it says: download parity-ethereum from the internet.

However, yes, if you're creating your own production app, it would make sense to pre-fetch it and bundle it inside the app. That's what we're doing in Fether: see https://github.com/paritytech/fether/issues/204.
