### ISSUE TITLE
Add changelogs

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/js-libs#96]
#93 introduces a breaking change, we should write changelogs right after.

Maybe with something like https://github.com/lerna/lerna-changelog?

**Comment by axelchalon** [comment]
sounds good!

**Comment by ltfschoen** [comment]
We'll need to update lerna, and hopefully soon with https://github.com/paritytech/js-libs/issues/28

**Comment by axelchalon** [comment]
Changelogs are now implemented since https://github.com/paritytech/js-libs/pull/93/commits/d80eb903aea029e4385d83d4d261b92c66199cc6

We're now using `lerna version --conventional-commits` in the CI to tag and publish a new release. This takes care of two things:
- Bump the version of the packages and root workspace (incl. dependencies to the other packages within the monorepo) with patch, minor or major automatically depending on the commit messages since the latest tag.
- Generate CHANGELOG.md at the root and for each package

The only thing we need to do to make this work is respect the specs from https://www.conventionalcommits.org/ (I would suggest squash merging the PRs with a conventional-commits-compliant commit message from now on)

**Comment by amaurymartiny** [comment]
Do you know what happens if we don't squash-merge with a conventional commit message? I suppose (and hope) no version bumping would happen?
